version: 2.1
  
jobs:
  build:
    docker:
      - image: circleci/node:16
 
    steps:
      - checkout
 
      # Install dependencies
      - run:
          name: Install Node.js dependencies
          command: npm install
 
      # Run tests
      - run:
          name: Run tests
          command: npm test

      # Start Docker daemon
      - setup_remote_docker:
          version: 19.03.13

      # Build Docker image upon successful tests
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/uems-image:latest .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/uems-image:latest
 
workflows:
  version: 2
  test:
    jobs:
      - build
